spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}
###############################---eureka---##############################
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER}/eureka/
###############################---端口---##############################
server:
  port: 8080