spring:
  profiles:
    active: ${ENV:prod}
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/pingtai?useUnicode=true&characterEncoding=UTF8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:root}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启后，就不用配path了，自动就
          lowerCaseServiceId: true
###############################---management---##############################
management:
  endpoints:
    web:
      exposure:
        include: '*'
###############################---eureka---##############################
eureka:
  instance:
    prefer-ip-address: true
###############################---jwt---##############################
jwt:
  # 加密秘钥
  secret: f4e2e5203434xx1WET12^%3^(WE45
  # token有效时长，7天，单位秒
  expire: 604800
  header: token
###############################---log---##############################
logging:
  file: ./logback.log